# This module detects the leftover heat left by a human
# We assume the scenario: A human leaves heat residual when he stands up and leaves the bed.
# The signature of heat residual: 
#  1. The temperature is lower than human body temperature, but higher than background temperature
#  2. It was associated with a human blob in previous frames
# How to detect: 
#  when a new blob is generated by tracking module, we are given: 
#   1. the mask of the new blob
#   2. the mask of all remaining blobs
#   3. The masks of all blobs in previous frames
# we first check for all remaining blobs' previous frames, which has largest overlap with the new blob
# if the overlap exceeds a threshold, we can assume one of the two blobs are residual
# we then compare the temperature of the two blobs. the lower temperature one is residual
import numpy as np
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

class ResidualHeatDetector:
    def __init__(self, temp_diff_threshold=2.0, overlap_threshold=0.7):
        self.temp_diff_threshold = temp_diff_threshold
        self.overlap_threshold = overlap_threshold

    # calculate the percentage of mask 1 covered by mask 2
    def _compute_coverage(self, mask1, mask2):
        intersection = np.logical_and(mask1, mask2).sum()
        union = mask1.sum()
        if union == 0:
            return 0.0
        return intersection / union

    def get_residual_index(self, blobs, new_blob):
        for idx, blob in enumerate(blobs):
            # we calculate the percentage of new blobs that is covered by existing blob's previous mask
            coverage = self._compute_coverage(new_blob.mask, blob.prev_mask)
            if coverage >= self.overlap_threshold:
                # check temperature difference
                temp_diff = blob.mean_temp - new_blob.mean_temp
                if temp_diff <= 0: # blob is colder than new blob, indicating it is residual
                    return idx
                else:
                    return -1
        return None
                
if __name__ == "__main__":
    from dataset import ThermalDataset
    from heatsource_detection_module.extract import HeatSourceDetector
    from presence_detection_workspace.unused.track_kalman import Tracker
    from data_collection_module import utils
    import cv2

    dataset = ThermalDataset("/Users/entomophile/Desktop/FYP/entry_exit_detection/presence_detection_workspace/data/hall1")
    detector = HeatSourceDetector()
    tracker = Tracker()

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    IRA_height, IRA_width = dataset.get_ira_highres(0).shape
    out = cv2.VideoWriter('kalman.mp4', fourcc, 30.0, (IRA_width, IRA_height))

    for idx in range(10505, 10530): #18115
        ira_highres = dataset.get_ira_highres(idx)
        thresh, mask = detector.get_thresh_mask_otsu(ira_highres)
        cleaned_mask = detector.get_connected_components(mask, min_size=10)
        tracker.update_blobs(cleaned_mask, ira_highres, detector.get_unmasked_mean(ira_highres, mask))

        ira_color = utils.colorize_thermal_map(ira_highres)
        for i, blob in enumerate(tracker.blobs):
            if len(blob.kalman_centroid_history) == 0:
                continue
            cX, cY = blob.kalman_centroid_history[-1]
            cv2.putText(ira_color, str(i), (int(cX), int(cY)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
        out.write(ira_color)
    out.release()